### ISSUE TITLE
No documentation on IDepositStatistics

### ISSUE THREAD

**Issue by Alexikon** [htl-perg-2019-20-5ahif/cash-desk-exercise-Alexikon#1]
In Contracts.cs there is no documentation on what to do with IDepositStatistics.

```
public interface IDepositStatistics
    {
        IMember Member { get; }

        int Year { get; }

        decimal TotalAmount { get; }
    }
``` 
thats how it currently looks like

I am currently doing my homework and I just found out, that there is no documentation on that interface. Until there is a documentation, I assume that everything has a `[Required]`.
Or is IDepositStatistics even in the Database?

Furthermore, the link to EF Cheat Sheet is broken. (But I know where to find it.)

**Comment by rstropek** [comment]
Not sure if it is still relevant: `IDepositStatistics` is used as the return type [here](https://github.com/htl-perg-2019-20-5ahif/cash-desk-exercise-Alexikon/blob/f0715fc16716c945e1c275bf5ab4a17381439032/CashDesk/Implementation.cs#L30).

EF Cheat Sheet Link: Which link to do mean? I would like to fix it.
